server:
  port: 8081

spring:
  application:
    name: auth-service
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:127.0.0.1:8848}
      config:
        server-addr: ${NACOS_ADDR:127.0.0.1:8848}
        file-extension: yaml
        refresh-enabled: true

  config:
    import:
      - optional:nacos:common.yaml
      - optional:nacos:auth-service.yaml

  mail:
    host: smtp.qq.com
    port: 587
    username: 1649182810@qq.com
    password: tpywidoemlinfagh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  data:
    redis:
      host: localhost
      port: 6379
      password:
      timeout: 2000ms

  datasource:
    url: jdbc:mysql://localhost:3307/jobspring_auth?useSSL=false&serverTimezone=Asia/Singapore&characterEncoding=utf8
    username: jobspring_user
    password: jobspring_pass
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  flyway:
    enabled: true

app:
  mail:
    from: 1649182810@qq.com

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT:http://127.0.0.1:9411/api/v2/spans}

management.endpoints.web.exposure.include: health,info