server:
  port: 8080

spring:
  application:
    name: job-service
  datasource:
    url: jdbc:mysql:///jobspring_job?cloudSqlInstance=${CLOUD_SQL_CONNECTION_NAME}&socketFactory=com.google.cloud.sql.mysql.SocketFactory&user=${DB_USER}&password=${DB_PASS}&useSSL=false&serverTimezone=Asia/Singapore&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  flyway:
    enabled: true

  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:nacos-service:8848}

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT:http://127.0.0.1:9411/api/v2/spans}

logging:
  level:
    root: INFO
    com.jobspring: INFO