server:
  port: 8086

spring:
  application:
    name: notification-service
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:127.0.0.1:8848}
  mail:
    host: smtp.qq.com
    port: 587
    username: 1649182810@qq.com
    password: tpywidoemlinfagh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  data:
    redis:
      host: localhost
      port: 6379
      password:
      timeout: 2000ms

app:
  mail:
    from: 1649182810@qq.com

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT:http://127.0.0.1:9411/api/v2/spans}

management.endpoints.web.exposure.include: ""