server:
  port: ${PORT:8080}

spring:
  application:
    name: notification-service
  cloud:
    discovery:
      enabled: false
    nacos:
      discovery:
        enabled: false
      config:
        enabled: false

  mail:
    host: ${MAIL_HOST:smtp.qq.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

app:
  mail:
    from: ${MAIL_FROM}

management.endpoints.web.exposure.include: "*"