version: "3.8"

networks:
  jobspring:
    driver: bridge

services:
  zipkin:
    image: openzipkin/zipkin:2.24
    container_name: zipkin
    ports:
      - "${ZIPKIN_PORT:-9411}:9411"
    networks: [jobspring]

  nacos:
    image: nacos/nacos-server:v2.3.2
    container_name: nacos
    platform: linux/amd64
    environment:
      - MODE=standalone
      - NACOS_AUTH_ENABLE=false
    ports:
      - "${NACOS_HTTP_PORT:-8848}:8848"
      - "${NACOS_GRPC_PORT:-9848}:9848"
      - "${NACOS_GRPCS_PORT:-9849}:9849"
    networks: [jobspring]
    profiles: ["all"]