server:
  port: ${PORT:8080}

spring:
  application:
    name: gateway-service
  cloud:
    discovery:
      enabled: false
    nacos:
      discovery:
        enabled: false
      config:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: false
      httpclient:
        connect-timeout: 2000
        response-timeout: 15s
      default-filters:
        - name: CircuitBreaker
          args:
            name: gwDefault
            fallbackUri: forward:/__gw_fallback
        - name: Retry
          args:
            retries: 1
            methods: GET
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - http://localhost:5173
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: auth
          uri: ${AUTH_BASE_URL}
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=2
            - RemoveRequestHeader=Authorization

        - id: user
          uri: ${USER_BASE_URL}
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=2
            - RemoveRequestHeader=Authorization

        - id: company
          uri: ${COMPANY_BASE_URL}
          predicates:
            - Path=/api/company/**
          filters:
            - StripPrefix=2
            - RemoveRequestHeader=Authorization

        - id: job
          uri: ${JOB_BASE_URL}
          predicates:
            - Path=/api/job/**
          filters:
            - StripPrefix=2
            - RemoveRequestHeader=Authorization

        - id: application
          uri: ${APPLICATION_BASE_URL}
          predicates:
            - Path=/api/application/**
          filters:
            - StripPrefix=2
            - RemoveRequestHeader=Authorization

        - id: notification
          uri: ${NOTIFICATION_BASE_URL}
          predicates:
            - Path=/api/notification/**
          filters:
            - StripPrefix=2
            - RemoveRequestHeader=Authorization

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT:http://127.0.0.1:9411/api/v2/spans}

resilience4j:
  circuitbreaker:
    instances:
      gwDefault:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 20
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
  timelimiter:
    instances:
      gwDefault:
        timeout-duration: 15s
        cancel-running-future: true

jwt:
  secret: ${JWT_SECRET:}