server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:127.0.0.1:8848}
      config:
        server-addr: ${NACOS_ADDR:127.0.0.1:8848}
        file-extension: yaml
        refresh-enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      httpclient:
        connect-timeout: 3000
        response-timeout: 20s
      default-filters:
        - name: Retry
          args:
            retries: 2
            methods: GET
            backoff:
              firstBackoff: 200ms
              maxBackoff: 1000ms
              factor: 2
        - name: CircuitBreaker
          args:
            name: gwDefault
            fallbackUri: forward:/__gw_fallback

      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - http://localhost:5173
              - http://localhost:3000
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

      routes:
        - id: auth
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=2
        - id: job
          uri: lb://job-service
          predicates:
            - Path=/api/job/**
          filters:
            - StripPrefix=2
        - id: user
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=2
        - id: company
          uri: lb://company-service
          predicates:
            - Path=/api/company/**
          filters:
            - StripPrefix=2
        - id: application
          uri: lb://application-service
          predicates:
            - Path=/api/application/**
          filters:
            - StripPrefix=2
        - id: notification
          uri: lb://notification-service
          predicates:
            - Path=/api/notification/**
          filters:
            - StripPrefix=2
  config:
    import:
      - optional:nacos:common.yaml
      - optional:nacos:gateway-service.yaml

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT:http://127.0.0.1:9411/api/v2/spans}
  endpoints:
    web:
      exposure:
        include: "*"

resilience4j:
  circuitbreaker:
    instances:
      gwDefault:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 20
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
  timelimiter:
    instances:
      gwDefault:
        timeout-duration: 10s
        cancel-running-future: true
