server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:127.0.0.1:8848}
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**, /ping
          filters:
            - StripPrefix=2
        - id: job
          uri: lb://job-service
          predicates:
            - Path=/api/job/**
          filters:
            - StripPrefix=2
        - id: user
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=2
        - id: company
          uri: lb://company-service
          predicates:
            - Path=/api/company/**
          filters:
            - StripPrefix=2
        - id: application
          uri: lb://application-service
          predicates:
            - Path=/api/application/**
          filters:
            - StripPrefix=2
        - id: notification
          uri: lb://notification-service
          predicates:
            - Path=/api/notification/**
          filters:
            - StripPrefix=2

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT:http://127.0.0.1:9411/api/v2/spans}

management.endpoints.web.exposure.include: ""