server:
  port: 8084

spring:
  application:
    name: company-service
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:127.0.0.1:8848}

  datasource:
    url: jdbc:mysql://localhost:3307/jobspring_company?useSSL=false&serverTimezone=Asia/Singapore&characterEncoding=utf8
    username: jobspring_user
    password: jobspring_pass
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  flyway:
    enabled: true
    locations: classpath:db/migration
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT:http://127.0.0.1:9411/api/v2/spans}

management.endpoints.web.exposure.include: ""