name: CI - Backend

on:
  pull_request:
    branches: [ "main", "master" ]
  push:
    branches: [ "main" ]

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven
      - name: Checkstyle at root
        run: mvn -B -q -DskipTests=true checkstyle:check

  build-test:
    needs: checkstyle
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        module:
          - common
          - auth-service
          - user-service
          - company-service
          - job-service
          - application-service
          - notification-service
          - gateway-service
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven
      - name: Build & Test (this module + deps)
        run: mvn -B -U -pl ${{ matrix.module }} -am clean verify
      - name: Upload surefire reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-${{ matrix.module }}
          path: |
            ${{ matrix.module }}/**/target/surefire-reports/*.xml
            **/${{ matrix.module }}/target/surefire-reports/*.xml
          if-no-files-found: ignore
      - name: Upload JaCoCo coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-${{ matrix.module }}
          path: |
            ${{ matrix.module }}/**/target/site/jacoco/jacoco.xml
            **/${{ matrix.module }}/target/site/jacoco/jacoco.xml
          if-no-files-found: ignore