name: Deploy auth-service (Cloud Run)

on:
  push:
    branches: [ master ]
    paths:
      - 'auth-service/**'
      - '.github/workflows/deploy-auth.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    env:
      REGION: asia-southeast1
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      REPO: jobspring-docker
      SERVICE: auth-service
      IMAGE_URI: asia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/jobspring-docker/auth-service:${{ github.sha }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Enable APIs
        run: |
          gcloud services enable run.googleapis.com sqladmin.googleapis.com artifactregistry.googleapis.com secretmanager.googleapis.com

      - name: Build & Push image with Jib
        run: |
          IMAGE="asia-southeast1-docker.pkg.dev/${PROJECT_ID}/${REPO}/${SERVICE}:${GITHUB_SHA}"
          mvn -f ${SERVICE}/pom.xml -DskipTests \
            com.google.cloud.tools:jib-maven-plugin:3.4.1:build \
            -Djib.to.image=$IMAGE

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${SERVICE} \
            --region=${REGION} \
            --image=${IMAGE_URI} \
            --platform=managed \
            --allow-unauthenticated \
            --add-cloudsql-instances="${{ secrets.CLOUD_SQL_CONN }}" \
            --set-env-vars=CLOUD_SQL_CONNECTION_NAME="${{ secrets.CLOUD_SQL_CONN }}",SPRING_PROFILES_ACTIVE=prod \
            --set-secrets=DB_USER=DB_USER:latest,DB_PASS=DB_PASS:latest,MAIL_USERNAME=MAIL_USERNAME:latest,MAIL_PASSWORD=MAIL_PASSWORD:latest \
            --service-account="${{ secrets.RUNTIME_SA }}" \
            --memory=512Mi --cpu=1 --concurrency=80 --min-instances=0