name: Deploy gateway-service (Cloud Run)

on:
  push:
    branches: [ master ]
    paths:
      - 'gateway-service/**'
      - '.github/workflows/deploy-gateway.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    env:
      REGION: asia-southeast1
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      REPO: jobspring-docker
      SERVICE: gateway-service
      IMAGE_URI: asia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/jobspring-docker/gateway-service:${{ github.sha }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Enable APIs
        run: |
          gcloud services enable run.googleapis.com artifactregistry.googleapis.com

      - name: Build & Push image with Jib
        run: |
          IMAGE="asia-southeast1-docker.pkg.dev/${PROJECT_ID}/${REPO}/${SERVICE}:${GITHUB_SHA}"
          mvn -pl ${SERVICE} -am -DskipTests clean compile jib:build -Dimage=$IMAGE

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${SERVICE} \
            --region=${REGION} \
            --image=${IMAGE_URI} \
            --platform=managed \
            --allow-unauthenticated \
            --service-account="${{ secrets.RUNTIME_SA }}" \
            --set-env-vars=SPRING_PROFILES_ACTIVE=prod \,AUTH_BASE_URL="${{ secrets.AUTH_BASE_URL }}" \,USER_BASE_URL="${{ secrets.USER_BASE_URL }}" \,COMPANY_BASE_URL="${{ secrets.COMPANY_BASE_URL }}" \,JOB_BASE_URL="${{ secrets.JOB_BASE_URL }}" \,APPLICATION_BASE_URL="${{ secrets.APPLICATION_BASE_URL }}" \,NOTIFICATION_BASE_URL="${{ secrets.NOTIFICATION_BASE_URL }}" \
            --set-secrets=JWT_SECRET=JWT_SECRET:latest \
            --memory=512Mi --cpu=1 --concurrency=80 --min-instances=0